[SPIKE][PAYSHIP-3046] Order capture retry
PrestaShopCorp/ps_checkout pull request #1275
Opened 2024-10-09 11:50 UTC by L3RAZ

2024-10-28 13:48 UTC, Matt75 approved these changes

2024-11-07 14:04 UTC, seiwan requested changes

2024-11-07 14:04 UTC, seiwan commented on src/PayPal/Order/PaypalOrderDataProvider.php
> +        if ($this->payPalOrder && isset($this->payPalOrder->getPaymentSource()[$this->payPalOrder->getFundingSource()])) {
```suggestion
        $fundingSource = $this->payPalOrder->getFundingSource();
        
        if ($this->payPalOrder && isset($this->payPalOrder->getPaymentSource()[$undingSource])) {
```

2024-11-07 14:04 UTC, seiwan commented on src/PayPal/Order/PaypalOrderDataProvider.php
>              $paymentSource = $this->payPalOrder->getPaymentSource()[$this->payPalOrder->getFundingSource()];
```suggestion
            $paymentSource = $this->payPalOrder->getPaymentSource()[$fundingSource];
```

2024-11-07 14:04 UTC, seiwan commented on src/PayPal/Order/PaypalOrderDataProvider.php
>              if ($this->payPalOrder->getFundingSource() === 'card') {
```suggestion
            if ($fundingSource === 'card') {
```

2024-11-08 09:49 UTC, L3RAZ commented on controllers/front/payment.php
> +        return $this->context->customer && $this->context->cart;
@seiwan So guest customers can reach this page, because this page will also be available for all payment methods, not just vaulting.

2024-11-12 08:56 UTC, seiwan requested changes

2024-11-12 08:56 UTC, seiwan commented on src/PayPal/Order/Cache/PayPalOrderCache.php
>      public function set($key, $value, $ttl = null)
PhpStan CR

2024-11-12 15:53 UTC, Matt75 approved these changes

2024-11-14 12:59 UTC, merged