[PAYSHIP-3149] PrestaShop 9 compatibility
PrestaShopCorp/ps_checkout pull request #1304
Opened 2024-12-13 15:13 UTC by L3RAZ

2025-01-06 15:17 UTC, seiwan commented on src/Order/CommandHandler/UpdateOrderStatusCommandHandler.php
> +//        $this->eventDispatcher->dispatch(new OrderStatusUpdatedEvent($orderStateId));
Maybe we can remove it if it's not used anymore ?

2025-01-06 15:17 UTC, seiwan commented on src/Order/Matrice/CommandHandler/UpdateOrderMatriceCommandHandler.php
> +//        if (!empty($res)) {
Maybe we can remove it if it's not used anymore ?

2025-01-06 15:17 UTC, seiwan commented on src/PayPal/PaymentToken/Query/GetCustomerPaymentTokensQueryHandler.php
>  //        $paymentTokens = $this->paymentTokenRepository->findByPrestaShopCustomerId($query->getCustomerId()->getValue(), $query->getPageSize(), $query->getPageNumber());
Maybe we can remove it if it's not used anymore ?

2025-01-06 15:17 UTC, seiwan commented on src/Repository/PsCheckoutCartRepository.php
> +//        if ($this->cartPrestaShopCache->hasItem(CacheSettings::CART_ID . $cartId)) {
Maybe we can remove it if it's not used anymore ?

2025-01-06 15:17 UTC, seiwan commented on src/Repository/PsCheckoutCartRepository.php
> +//            $this->cartPrestaShopCache->setMultiple([
Maybe we can remove it if it's not used anymore ?

2025-01-06 15:17 UTC, seiwan commented on src/Repository/PsCheckoutCartRepository.php
> +//            $this->cartPrestaShopCache->setMultiple([
Maybe we can remove it if it's not used anymore ?

2025-01-15 09:27 UTC, kpodemski commented on controllers/front/webhook.php
> +    protected function geolocationManagement($default_country)
same as above, what's the point of this change?

2025-01-15 09:27 UTC, kpodemski commented on ps_checkout.php
> +        $this->updatePosition(\Hook::getIdByName('paymentOptions'), false, 1);
```suggestion
        $this->updatePosition(Hook::getIdByName('paymentOptions'), false, 1);
```

you are not using namespaces here, right?

2025-01-15 09:27 UTC, kpodemski commented on ps_checkout.php
>          return $this->context->link->getPageLink(
It's a tiny detail but `$this->context->link->getPageLink('order')` would've been enough

2025-01-15 09:27 UTC, kpodemski commented on src/Order/CommandHandler/AddOrderPaymentCommandHandler.php
> +//        $this->eventDispatcher->dispatch(new OrderPaymentCreatedEvent((int) $latestOrderPayment->id));
:)

2025-01-15 09:27 UTC, kpodemski commented on src/PayPal/Order/EventProcessor/PayPalOrderEventProcessor.php
> +    public function __construct(
For PS9 you can use constructor property promotion

2025-01-15 09:27 UTC, kpodemski commented on src/PayPal/Order/PayPalOrderPresenter.php
> +        return \Context::getContext()->getCurrentLocale()->formatPrice((float) $this->paypalOrderDataProvider->getTotalAmount(), $this->paypalOrderDataProvider->getCurrencyCode());
```suggestion
        return \Context::getContext()->getCurrentLocale()->formatPrice((float) $this->paypalOrderDataProvider->getTotalAmount(), $this->paypalOrderDataProvider->getCurrencyCode());
```

I think this could be simplified with `Tools::getContextLocale`

2025-01-15 09:27 UTC, kpodemski commented on src/PaypalCountryCodeMatrice.php
> +        return in_array($isoCode, self::MATCH_ISO_CODE);
Something is off here, I think, because if the purpose is that you return the mapped value if it exists in the static then it will not do that after your change if I'm not wrong.

```
public function getPrestashopIsoCode($isoCode)
{
    if (!is_string($isoCode)) {
        return false;
    }

    $mappedCode = array_search($isoCode, self::MATCH_ISO_CODE);
    if ($mappedCode !== false) {
        return $mappedCode;
    }

    return $isoCode;
}
```

2025-01-15 09:27 UTC, kpodemski commented on views/templates/hook/displayOrderConfirmation.tpl
>              {$translations.notificationPendingApproval|escape:'html':'UTF-8'}
```suggestion
            {$translations.notificationPendingApproval}
```

using such escapes in front office templates is no longer required

2025-01-15 10:06 UTC, seiwan requested changes

2025-01-15 14:34 UTC, jolelievre reviewed
Thanks @L3RAZ for this huge work

I have a few questions, sorry if they don't make sens it's probably because I lack knowledge on this module's code 😅

2025-01-15 14:34 UTC, jolelievre commented on config/common.yml
> +    factory: [ '@PrestaShop\Module\PrestashopCheckout\CommandBus\TacticianQueryBusFactory', "create" ]
In PrestaShop V9 we removed tactician in favor of Symfony Messenger as the middleware that handles the command bus

I'm not sure forcing a custom integration of tactician in this module is a good idea, ideally you should rely on the core messenger like any other CQRS commands The migration is quite straight forward actually you just need to add this attribute on the handler class `#[AsCommandHandler]` and add `autowire` and `autoconfigure` on the handler service definition

2025-01-15 14:34 UTC, jolelievre commented on config/common.yml
> +      - PrestaShop\Module\PrestashopCheckout\Order\Command\AddOrderPaymentCommand: ['@PrestaShop\Module\PrestashopCheckout\Order\CommandHandler\AddOrderPaymentCommandHandler']
I agree (see my comment above) you should relay on the core command bus instead of an internal implementation

2025-01-15 14:34 UTC, jolelievre commented on config/common.yml
> +      - PrestaShop\Module\PrestashopCheckout\Order\Command\AddOrderPaymentCommand: ['@PrestaShop\Module\PrestashopCheckout\Order\CommandHandler\AddOrderPaymentCommandHandler']
Also using autowiring on your services (along with explicit type for service injections) should greatly simplify the service definitions

2025-01-15 14:34 UTC, jolelievre commented on config/common.yml
> +    factory: [ '@PrestaShop\Module\PrestashopCheckout\Event\SymfonyEventDispatcherFactory', "create" ]
Quick question as I don't know the details of this module, but why do you need a specific event dispatcher? What does it do that the regular global event dispatcher from Symfony can't do?

Maybe it's because those services are also used on the FO, in a legacy environment that doesn't include the Symfony event dispatcher?

2025-01-15 14:34 UTC, jolelievre commented on config/common.yml
> +    factory: [ '@PrestaShop\Module\PrestashopCheckout\Event\SymfonyEventDispatcherFactory', "create" ]
Another question however, what is the difference between `ps_checkout.event.dispatcher.symfony` and `ps_checkout.event.dispatcher.symfony2` I mean I see that they don't have the same subscribers but why? 

Shouldn't the initial `ps_checkout.event.dispatcher.symfony` be cleaned if not used anymore? or maybe simply modified to match this new need?

2025-01-15 14:34 UTC, jolelievre commented on config/common.yml
> +    factory: [ '@PrestaShop\Module\PrestashopCheckout\CommandBus\TacticianQueryBusFactory', "create" ]
Oh actually I noticed that the CQRS commands are also used in FO controllers, I guess that explains the need for this custom bus right?

2025-01-15 14:34 UTC, jolelievre commented on src/Checkout/EventSubscriber/CheckoutEventSubscriber.php
> +        CapturePayPalOrderCommandHandler $capturePayPalOrderCommandHandler
```suggestion
        private readonly CheckoutChecker $checkoutChecker,
        private readonly PsCheckoutCartRepository $psCheckoutCartRepository,
        private readonly QueryBusInterface $queryBus,
        private readonly UpdatePaymentMethodSelectedCommandHandler $updatePaymentMethodSelectedCommandHandler,
        private readonly CreateOrderCommandHandler $createOrderCommandHandler,
        private readonly CapturePayPalOrderCommandHandler $capturePayPalOrderCommandHandler
```
Little tip since you now use PHP 8.1 minimum, you can use the property promotion feature, if you want, that greatly decreases the quantity of code https://www.php.net/manual/en/language.oop5.decon.php#language.oop5.decon.constructor.promotion

2025-01-15 14:34 UTC, jolelievre commented on src/CommandBus/TacticianCommandBusAdapter.php
> +use PrestaShopBundle\CommandBus\MessengerCommandBus;
Ah seems like you actually do use the `MessengerCommandBus` adpter from the core, my bad I was misled by the name of this class But since it's no longer based on Tactitian maybe it should be renamed as well (along with its factory)?

2025-01-15 14:34 UTC, jolelievre commented on src/Order/CommandHandler/AddOrderPaymentCommandHandler.php
> +    public function __invoke(AddOrderPaymentCommand $command) {
By the way, if you use the `AsCommandHandler` you shouldn't need to add this `__invoke` method, but again I'm really aware of this module's architecture and context If the command/query buses are used in FO/legacy context this auto-configuration will probably not work

2025-01-16 14:41 UTC, L3RAZ commented on src/Order/CommandHandler/AddOrderPaymentCommandHandler.php
> +    public function __invoke(AddOrderPaymentCommand $command) {
I will check if this works on front controllers

2025-01-17 12:14 UTC, L3RAZ commented on config/common.yml
> +    factory: [ '@PrestaShop\Module\PrestashopCheckout\Event\SymfonyEventDispatcherFactory', "create" ]
I added the second event dispatcher because we have a circular dependency in one command handler. So the first event dispatcher calls CaptureOrderCommandHandler and the second event dispatcher is injected into the command handler

2025-01-17 12:16 UTC, L3RAZ commented on config/common.yml
> +    factory: [ '@PrestaShop\Module\PrestashopCheckout\CommandBus\TacticianQueryBusFactory', "create" ]
Yes, I guess so. But I would need to make some tests, because this code comes from as far as PS 1.7 and probably there wasn't a command handler back then

2025-01-21 10:09 UTC, seiwan requested changes

2025-01-21 10:09 UTC, seiwan commented on src/PayPal/Sdk/PayPalSdkConfigurationBuilder.php
> +        private  FundingSourceEligibilityConstraint $fundingSourceEligibilityConstraint,
```suggestion
        private FundingSourceEligibilityConstraint $fundingSourceEligibilityConstraint,
```

2025-01-21 10:29 UTC, L3RAZ commented on controllers/front/DispatchWebHook.php
> +    protected function geolocationManagement($defaultCountry)
$defaultCountry is the correct name

2025-01-29 16:58 UTC, PSebou commented on .github/workflows/php.yml
> +    name: PHP Syntax check 8.1|8.2|8.2
maybe we can just have 8.1|8.2 or 8.1|8.2|8.3

2025-01-31 08:44 UTC, L3RAZ commented on .github/workflows/php.yml
> +    name: PHP Syntax check 8.1|8.2|8.2
Yes, I added a typo, it should be 8.1|8.2|8.3

2025-02-03 16:31 UTC, seiwan requested changes

2025-02-04 09:38 UTC, L3RAZ commented on controllers/admin/AdminPaypalOnboardingPrestashopCheckoutController.php
> +    public function isAnonymousAllowed()
Yes, in PS9 AdminControllerCore class it's public

2025-02-04 09:39 UTC, L3RAZ commented on ps_checkout.php
> +    private ?bool $merchantIsValid;
The whole point is to not check if merchant is valid multiple times. If it's null - we set the value. If it's bool - we know if it's valid or not

2025-02-10 13:07 UTC, L3RAZ commented on controllers/admin/AdminAjaxPrestashopCheckoutController.php
> +    }
We would also need to modify BO SDK for it, because the expected response is true/false

2025-02-11 08:16 UTC, Matt75 commented on controllers/admin/AdminAjaxPrestashopCheckoutController.php
> +    }
Are we handle the response content on BO-SDK? Or we rely only on http status code?

2025-02-11 08:22 UTC, L3RAZ commented on controllers/admin/AdminAjaxPrestashopCheckoutController.php
> +    }
We check response content

2025-02-11 08:46 UTC, Matt75 commented on controllers/admin/AdminAjaxPrestashopCheckoutController.php
> +    }
Ok let's keep it like that...

2025-02-11 15:47 UTC, Matt75 approved these changes

2025-02-12 15:41 UTC, Matt75 approved these changes

2025-02-18 08:41 UTC, matks reviewed
I approve commits
- https://github.com/PrestaShopCorp/ps_checkout/pull/1304/commits/fb006750d675e1d8f616fd1763c5792be586a5c3
- https://github.com/PrestaShopCorp/ps_checkout/pull/1304/commits/6e46e8f3ebcd57ff8359b819beeff56ad7c79352

But as I'm not a checkout expert I prefer to wait for a 2nd review ;)

2025-02-18 08:55 UTC, Matt75 approved these changes

2025-02-25 10:05 UTC, merged