Save PayPal country merchant in ps_configuration
PrestaShopCorp/ps_checkout pull request #700
Opened 2021-02-17 15:35 UTC by seiwan

2021-02-17 17:44 UTC, Rzial requested changes

2021-02-17 17:44 UTC, Rzial commented on src/Repository/PaypalAccountRepository.php
> +     * Get the merchant email
Typo here!

2021-02-18 08:17 UTC, Matt75 requested changes

2021-02-18 08:17 UTC, Matt75 commented on src/Repository/PaypalAccountRepository.php
>              $this->getCardHostedFieldsStatus()
Constructor params moved
```suggestion
            $this->getMerchantEmailStatus(),
            $this->getPaypalPaymentStatus(),
            $this->getCardHostedFieldsStatus()
            $this->getMerchantCountry(),
```

2021-02-19 16:04 UTC, Rzial approved these changes

2021-02-22 13:27 UTC, Matt75 approved these changes

2021-02-22 13:32 UTC, merged